### ISSUE TITLE
Noisy debugging statement at line 59 of optimization.js in Powell method...

### ISSUE THREAD

**Issue by RobertLRead** [iaroslav-ai/optimization-js#1]
in minimiize_Powell, at line 59 in optimization.js, there is a "console.log" statement.  This  is noisy even when the function appears to succeed, I suspect it is just a leftover debugging statement.

At line 216, there is a statement "console.log("fv =" + fx)".

**Comment by iaroslav-ai** [comment]
Yes this is exactly a leftover of debugging, removed. Thanks!
